Do not content type in blob metadata when it is null since that will cause a 400 Bad Request error
Example of the error in question:

hudson.AbortException: Failed to upload ... to ..., response: 400 Bad Request, body:
<?xml version='1.0' encoding='UTF-8'?>
<Error>
  <Code>MalformedSecurityHeader</Code>
  <Message>Your request has a malformed header.</Message>
  <ParameterName>content-type</ParameterName>
  <Details>Header was included in signedheaders, but not in the request.</Details>
</Error>